# Generated by Django 3.2.5 on 2022-01-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useradditionalinfo',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='useradditionalinfo',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinfo',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
