# Generated by Django 3.2.5 on 2022-01-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botapi', '0002_auto_20220105_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountmanager',
            old_name='name',
            new_name='accountmanager_name',
        ),
    ]
