# Generated by Django 3.2.5 on 2022-01-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapi', '0007_auto_20220105_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanager',
            name='manager_contact_no',
        ),
        migrations.AddField(
            model_name='usermanager',
            name='user_email',
            field=models.EmailField(max_length=40, null=True),
        ),
    ]
