# Generated by Django 3.2.5 on 2022-01-06 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botapi', '0008_auto_20220106_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapi.useradditionalinfo'),
        ),
    ]
