# Generated by Django 3.2.5 on 2022-01-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botapi', '0011_usermanager_manager_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanager',
            name='manager_name',
        ),
    ]
