# Generated by Django 3.2.5 on 2022-01-06 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botapi', '0013_usermanager_manager_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmanager',
            name='contact_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='usermanager',
            name='manager_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botapi.accountmanager'),
        ),
        migrations.DeleteModel(
            name='FinalAccountmanager',
        ),
    ]
